version: '3.4'
services:
  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "c:/users/abdulkadir/documents/programming/personal/datascience/zoomcamp/week1/docker_sql/ny_taxi_postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - airflow # created below as an external network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8081:80" # changed to 8081 for week 2 airflow as 8080 is being used by airflow
    # from week 2 airflow task, connecting this db to the airflow dag
    networks:
      - airflow # created below as an external network
networks:
  # default:
  #   external:
  #     name: pg-network
  # create external network for week 2 to connect airflow to this db
  airflow:
    external:
      name: de_airflow_default