install:
	pip install -r requirements.txt
twitter_data:
	python3 data/twitter_data.py
stocks_data:
	python3 data/stocks_data.py
kafka_read:
	python3 kafka/read_data_to_kafka.py
transform_data:
	python3 kafka/data_transformations.py
dashboard:
	python3 dashboard/dashboard.py